# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bo1O9I19qRbypf-V6d-Im8p1SfwdeGW6
"""

!pip install -q streamlit
!pip install -q pypdf
!pip install -q sentence-transformers
!pip install -q faiss-cpu
!pip install -q google-generativeai
!pip install -q langchain-text-splitters

import streamlit as st

st.set_page_config(
    page_title="Research Paper Assistant",
    layout="wide"
)

st.title(" Research Paper Assistant")

st.write(
    "Upload research papers and ask questions."
)

!streamlit run app.py

