# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bo1O9I19qRbypf-V6d-Im8p1SfwdeGW6
"""

!pip install -q streamlit
!pip install -q pypdf
!pip install -q sentence-transformers
!pip install -q faiss-cpu
!pip install -q google-generativeai
!pip install -q langchain-text-splitters

import streamlit as st

st.set_page_config(
    page_title="Research Paper Assistant",
    page_icon="📚",
    layout="wide"
)

st.title("📚 Research Paper Assistant")

st.markdown("""
Upload research papers and:

- Ask Questions
- Generate Literature Reviews
- Find Research Gaps
- Compare Papers
""")

st.divider()

uploaded_files = st.file_uploader(
    "Upload PDF Papers",
    type=["pdf"],
    accept_multiple_files=True
)

if uploaded_files:

    st.success(
        f"{len(uploaded_files)} paper(s) uploaded successfully."
    )

st.divider()

tool = st.sidebar.selectbox(
    "Choose Tool",
    [
        "Ask Questions",
        "Literature Review",
        "Research Gaps",
        "Compare Papers"
    ]
)

if tool == "Ask Questions":

    st.subheader("Ask Questions")

    question = st.text_input(
        "Enter your question"
    )

    if st.button("Submit"):

        st.info(
            "Backend will be connected here."
        )

elif tool == "Literature Review":

    st.subheader(
        "Generate Literature Review"
    )

    if st.button(
        "Generate Review"
    ):

        st.info(
            "Backend will be connected here."
        )

elif tool == "Research Gaps":

    st.subheader(
        "Research Gap Finder"
    )

    if st.button(
        "Find Gaps"
    ):

        st.info(
            "Backend will be connected here."
        )

elif tool == "Compare Papers":

    st.subheader(
        "Compare Papers"
    )

    if st.button(
        "Compare"
    ):

        st.info(
            "Backend will be connected here."
        )