# -*- coding: utf-8 -*-
"""rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GeVGro_oRbnR2slGzkqLKOmj2R6azz2N
"""

from pypdf import PdfReader
from langchain_text_splitters import RecursiveCharacterTextSplitter

from sentence_transformers import SentenceTransformer

import google.generativeai as genai

import numpy as np
import faiss
import re

embedding_model = SentenceTransformer(
    "BAAI/bge-small-en-v1.5"
)

model = genai.GenerativeModel(
    "gemini-2.5-flash"
)

"""Build Knowledge Base"""

def build_knowledge_base(uploaded_files):

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=100
    )

    chunk_data = []

    chunk_id = 0

    for pdf_file in uploaded_files:

        reader = PdfReader(pdf_file)

        text = ""

        for page in reader.pages:

            page_text = page.extract_text()

            if page_text:
                text += page_text + "\n"

        text = re.sub(r"\s+", " ", text)

        chunks = splitter.split_text(text)

        for chunk in chunks:

            chunk_data.append({
                "paper": pdf_file,
                "chunk_id": chunk_id,
                "text": chunk
            })

            chunk_id += 1

    texts = [
        item["text"]
        for item in chunk_data
    ]

    embeddings = embedding_model.encode(
        texts,
        show_progress_bar=True
    )

    index = faiss.IndexFlatL2(
        embeddings.shape[1]
    )

    index.add(
        np.array(embeddings).astype(
            "float32"
        )
    )

    return (
        chunk_data,
        embeddings,
        index
    )

"""Retrieve Chunks"""

def retrieve_chunks(
    query,
    chunk_data,
    embeddings,
    index,
    k=5
):

    query_embedding = embedding_model.encode(
        [query]
    )

    distances, indices = index.search(
        np.array(
            query_embedding
        ).astype("float32"),
        k
    )

    results = []

    for idx in indices[0]:

        results.append(
            chunk_data[idx]
        )

    return results

"""Paper-Aware Retrieval"""

def retrieve_by_paper(
    query,
    chunk_data,
    embeddings,
    k_per_paper=3
):

    query_embedding = embedding_model.encode(
        [query]
    )

    results = []

    papers = set(
        item["paper"]
        for item in chunk_data
    )

    for paper in papers:

        paper_indices = [
            i
            for i, item in enumerate(
                chunk_data
            )
            if item["paper"] == paper
        ]

        paper_embeddings = embeddings[
            paper_indices
        ]

        temp_index = faiss.IndexFlatL2(
            embeddings.shape[1]
        )

        temp_index.add(
            paper_embeddings.astype(
                "float32"
            )
        )

        D, I = temp_index.search(
            query_embedding.astype(
                "float32"
            ),
            k_per_paper
        )

        for idx in I[0]:

            original_idx = paper_indices[idx]

            results.append({
                "paper":
                    chunk_data[
                        original_idx
                    ]["paper"],

                "chunk_id":
                    chunk_data[
                        original_idx
                    ]["chunk_id"],

                "text":
                    chunk_data[
                        original_idx
                    ]["text"]
            })

    return results

"""Ask paper"""

def ask_paper(
    question,
    chunk_data,
    embeddings
):

    retrieved = retrieve_by_paper(
        question,
        chunk_data,
        embeddings,
        k_per_paper=3
    )

    context = ""

    for item in retrieved:

        context += f'''
Paper: {item["paper"]}

Content:
{item["text"]}

'''

    prompt = f"""
You are a research paper assistant.

Analyze information across multiple papers.

Use ONLY the provided context.

If information is missing,
say so explicitly.

Context:
{context}

Question:
{question}

Provide:

1. Answer

2. Evidence

3. Papers Referenced
"""

    response = model.generate_content(
        prompt
    )

    return {
        "answer": response.text,
        "sources": retrieved
    }

"""Show sources"""

def show_sources(result):

    for source in result["sources"]:

        print(
            source["paper"],
            "| Chunk:",
            source["chunk_id"]
        )