# -*- coding: utf-8 -*-
"""review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18xfubiQumgD9nwjWcwSgVLx3aCfYyt2r
"""

import google.generativeai as genai

"""Helper Function"""

def get_review_context(chunk_data):

    context = ""

    papers = set(
        item["paper"]
        for item in chunk_data
    )

    for paper in papers:

        paper_chunks = [
            item["text"]
            for item in chunk_data
            if item["paper"] == paper
        ]

        context += f"""
PAPER:
{paper}

"""

        context += "\n".join(
            paper_chunks[:10]
        )

        context += "\n\n"

    return context

"""Literature Review Generator"""

def generate_literature_review(
    chunk_data,
    model
):

    context = get_review_context(
        chunk_data
    )

    prompt = f"""
You are a research analyst.

Generate a structured literature review.

Context:
{context}

Create:

1. Introduction

2. Existing Methods

3. Key Findings

4. Limitations

5. Research Gaps

6. Future Directions
"""

    response = model.generate_content(
        prompt
    )

    return response.text

"""Research Gap Finder"""

def find_research_gaps(
    chunk_data,
    model
):

    context = get_review_context(
        chunk_data
    )

    prompt = f"""
Analyze the research papers.

Context:
{context}

Identify:

1. Common limitations

2. Open challenges

3. Missing research areas

4. Potential future work

5. Novel research directions
"""

    response = model.generate_content(
        prompt
    )

    return response.text

"""Compare Papers"""

def compare_papers(
    chunk_data,
    model
):

    context = get_review_context(
        chunk_data
    )

    prompt = f"""
Compare the uploaded papers.

Context:
{context}

Create a comparison table.

Compare:

- Objective

- Methodology

- Dataset

- Results

- Limitations

- Future Work
"""

    response = model.generate_content(
        prompt
    )

    return response.text

"""Executive Summary"""

def generate_executive_summary(
    chunk_data,
    model
):

    context = get_review_context(
        chunk_data
    )

    prompt = f"""
Summarize the uploaded papers.

Context:
{context}

Provide:

1. Main topic

2. Key findings

3. Important limitations

4. Overall conclusion

Keep it concise.
"""

    response = model.generate_content(
        prompt
    )

    return response.text